catalog/urls.py
from django.urls import path


from catalog.views import (
    index,
    LiteraryFormatListView,
    BookListView,
    BookCreateView,
    BookUpdateView,
    AuthorListView,
    AuthorDetailView,
    AuthorCreateView,
    BookDetailView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
#    test_session_view,
)

#   шлях, який оброблюється ф-єю  index
urlpatterns = [
    path("", index, name= "index"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name= "literary-format-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name= "literary-format-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name= "literary-format-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name= "literary-format-delete"),
    path("books/", BookListView.as_view(), name= "book-list"),
    path("books/create/", BookCreateView.as_view(), name= "book-create"),
    path("books/<int:pk>/", BookDetailView.as_view(), name= "book-detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name= "book-update"),
    path("authors/", AuthorListView.as_view(), name= "author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name= "author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name= "author-detail"),
    # path("books/<int:pk>", book_detail_view, name= "book-detail"),

#    path("test-session/", test_session_view, name= "test-session"),
]


app_name = "catalog"

templates/includes/footer.html
<!-- -------- START FOOTER 5 w/ DARK BACKGROUND ------- -->
<footer class="footer py-5">
  <div class="container z-index-1 position-relative">
    <div class="row">
      <div class="col-lg-4 me-auto mb-lg-0 mb-4 text-lg-start text-center">
        <h6 class="text-dark font-weight-bolder text-uppercase mb-lg-4 mb-3">Material Design</h6>
        <ul class="nav flex-row ms-n3 justify-content-lg-start justify-content-center mb-4 mt-sm-0">
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com/presentation?AFFILIATE=128200" target="_blank">
              About
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com/blog?AFFILIATE=128200" target="_blank">
              Blog
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">
              Services
            </a>
          </li>
        </ul>
        <p class="text-sm text-dark opacity-8 mb-0">
          &copy; <a href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed.
        </p>
      </div>
      <div class="col-lg-6 ms-auto text-lg-end text-center">
        <p class="mb-5 text-lg text-dark font-weight-bold">
          The reward for getting on the stage is fame. The price of fame is you can’t get off the stage.
        </p>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-dribbble"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-twitter"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-pinterest"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark opacity-5">
          <span class="fab fa-github"></span>
        </a>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{#{% load static %}#}
{#<!-- Navbar -->#}
{#<div class="container position-sticky z-index-sticky top-0">#}
{#  <div class="row">#}
{#    <div class="col-12">#}
{#      <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">#}
{#        <div class="container-fluid px-0">#}
{#          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'catalog:index' %}">#}
{#            Home#}
{#          </a>#}
{#          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"#}
{#                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"#}
{#                  aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon mt-2">#}
{#              <span class="navbar-toggler-bar bar1"></span>#}
{#              <span class="navbar-toggler-bar bar2"></span>#}
{#              <span class="navbar-toggler-bar bar3"></span>#}
{#            </span>#}
{#          </button>#}
{#          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">#}
{#            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">#}
{#              <li class="nav-item dropdown dropdown-hover mx-2">#}
{#                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"#}
{#                   href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                  Pages#}
{#                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">#}
{#                </a>#}
{#                <ul class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"#}
{#                    aria-labelledby="dropdownMenuPages">#}
{#                  <li>#}
{#                    <a href="/" class="dropdown-item border-radius-md">#}
{#                      <span class="ps-3">Presentation</span>#}
{#                    </a>#}
{#                  </li>#}
{#                </ul>#}
{#              </li>#}
{##}
{#              {% if request.user.is_authenticated %}#}
{#                <li class="nav-item ms-lg-auto">#}
{#                  <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">#}
{#                    <i class="fa fa-sign-out me-1"></i>#}
{#                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                       data-bs-placement="bottom" title="Logout">Logout</p>#}
{#                  </a>#}
{#                </li>#}
{#              {% else %}#}
{#                <li class="nav-item ms-lg-auto">#}
{#                  <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}">#}
{#                    <i class="fa fa-sign-in me-1"></i>#}
{#                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                       data-bs-placement="bottom" title="Login">Login</p>#}
{#                  </a>#}
{#                </li>#}
{#              {% endif %}#}
{##}
{#              <li class="nav-item my-auto ms-3 ms-lg-0">#}
{#                <a href="https://appseed.us/product/soft-ui-design/django/" target="_blank"#}
{#                   class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Download</a>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </div>#}
{#      </nav>#}
{#    </div>#}
{#  </div>#}
{#</div>#}

<!-- Navbar -->
{#<div class="container position-sticky z-index-sticky top-0">#}
{#  <div class="row">#}
{#    <div class="col-12">#}
{#      <nav#}
{#        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">#}
{#        <div class="container-fluid px-0">#}
{#          <a class="navbar-brand font-weight-bolder ms-sm-3"#}
{#            href="{% url "catalog:index" %}">#}
{#            Home#}
{#          </a>#}
{#          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"#}
{#            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"#}
{#            aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon mt-2">#}
{#              <span class="navbar-toggler-bar bar1"></span>#}
{#              <span class="navbar-toggler-bar bar2"></span>#}
{#              <span class="navbar-toggler-bar bar3"></span>#}
{#            </span>#}
{#          </button>#}
{#          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">#}
{#            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">#}
{#              <li class="nav-item dropdown dropdown-hover mx-2">#}
{#                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"#}
{#                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                  Pages#}
{#                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">#}
{#                </a>#}
{#                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"#}
{#                  aria-labelledby="dropdownMenuPages">#}
{#                  <div class="d-none d-lg-block">#}
{#                    <div#}
{#                      class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center px-0">#}
{#                      <div class="d-inline-block">#}
{#                        <div#}
{#                          class="icon icon-shape icon-xs border-radius-md bg-gradient-primary text-center me-2 d-flex align-items-center justify-content-center">#}
{#                          <svg width="12px" height="12px" viewBox="0 0 45 40" version="1.1"#}
{#                            xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">#}
{#                            <title>shop </title>#}
{#                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">#}
{#                              <g transform="translate(-1716.000000, -439.000000)" fill="#FFFFFF" fill-rule="nonzero">#}
{#                                <g transform="translate(1716.000000, 291.000000)">#}
{#                                  <g transform="translate(0.000000, 148.000000)">#}
{#                                    <path#}
{#                                      d="M46.7199583,10.7414583 L40.8449583,0.949791667 C40.4909749,0.360605034 39.8540131,0 39.1666667,0 L7.83333333,0 C7.1459869,0 6.50902508,0.360605034 6.15504167,0.949791667 L0.280041667,10.7414583 C0.0969176761,11.0460037 -1.23209662e-05,11.3946378 -1.23209662e-05,11.75 C-0.00758042603,16.0663731 3.48367543,19.5725301 7.80004167,19.5833333 L7.81570833,19.5833333 C9.75003686,19.5882688 11.6168794,18.8726691 13.0522917,17.5760417 C16.0171492,20.2556967 20.5292675,20.2556967 23.494125,17.5760417 C26.4604562,20.2616016 30.9794188,20.2616016 33.94575,17.5760417 C36.2421905,19.6477597 39.5441143,20.1708521 42.3684437,18.9103691 C45.1927731,17.649886 47.0084685,14.8428276 47.0000295,11.75 C47.0000295,11.3946378 46.9030823,11.0460037 46.7199583,10.7414583 Z"#}
{#                                      opacity="0.598981585"></path>#}
{#                                    <path#}
{#                                      d="M39.198,22.4912623 C37.3776246,22.4928106 35.5817531,22.0149171 33.951625,21.0951667 L33.92225,21.1107282 C31.1430221,22.6838032 27.9255001,22.9318916 24.9844167,21.7998837 C24.4750389,21.605469 23.9777983,21.3722567 23.4960833,21.1018359 L23.4745417,21.1129513 C20.6961809,22.6871153 17.4786145,22.9344611 14.5386667,21.7998837 C14.029926,21.6054643 13.533337,21.3722507 13.0522917,21.1018359 C11.4250962,22.0190609 9.63246555,22.4947009 7.81570833,22.4912623 C7.16510551,22.4842162 6.51607673,22.4173045 5.875,22.2911849 L5.875,44.7220845 C5.875,45.9498589 6.7517757,46.9451667 7.83333333,46.9451667 L19.5833333,46.9451667 L19.5833333,33.6066734 L27.4166667,33.6066734 L27.4166667,46.9451667 L39.1666667,46.9451667 C40.2482243,46.9451667 41.125,45.9498589 41.125,44.7220845 L41.125,22.2822926 C40.4887822,22.4116582 39.8442868,22.4815492 39.198,22.4912623 Z">#}
{#                                    </path>#}
{#                                  </g>#}
{#                                </g>#}
{#                              </g>#}
{#                            </g>#}
{#                          </svg>#}
{#                        </div>#}
{#                      </div>#}
{#                      Landing Pages#}
{#                    </div>#}
{#                    <a href="/" class="dropdown-item border-radius-md">#}
{#                      <span class="ps-3">Presentation</span>#}
{##}
{##}
{#              {% if request.user.is_authenticated %}#}
{#              <li class="nav-item ms-lg-auto">#}
{#                <a class="nav-link nav-link-icon me-2"#}
{#                  href="{% url 'logout' %}">#}
{#                  <i class="fa fa-sign-out me-1"></i>#}
{#                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                    data-bs-placement="bottom" title="Logout">Logout</p>#}
{#                </a>#}
{#              </li>#}
{#              {% else %}#}
{#              <li class="nav-item ms-lg-auto">#}
{#                <a class="nav-link nav-link-icon me-2"#}
{#                  href="{% url 'login' %}">#}
{#                  <i class="fa fa-sign-in me-1"></i>#}
{#                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                    data-bs-placement="bottom" title="Login">Login</p>#}
{#                </a>#}
{#              </li>#}
{#              {% endif %}#}
{##}
{#              <li class="nav-item my-auto ms-3 ms-lg-0">#}
{#                <a href="https://appseed.us/product/soft-ui-design/django/" target="_blank"#}
{#                  class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Download</a>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </div>#}
{#      </nav>#}
{#      <!-- End Navbar -->#}
{#    </div>#}
{#  </div>#}
{#</div>#}
{% load static %}
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'catalog:index' %}" rel="tooltip" title="Library System" data-placement="bottom">
            Inform Navigation
          </a>

          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>

          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalog:index' %}">Home</a>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                  <span class="nav-link disabled">User: {{ user.username }}</span>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
      {% endif %}
      <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
{% endif %}

templates/includes/sidebare.html
{% load static %}
{#<ul class="sidebar-nav">#}
{#  {% if user.is_authenticated %}#}
{#  <li>#}
{#    User: {{ user.username }}#}
{#  </li>#}
{#  <li>#}
{#      <a href="{% url 'logout' %}">Logout</a>#}
{#    </li>#}
{#  {% else %}#}
{#    <li>#}
{#      <a href="{% url 'login' %}">Login</a>#}
{#    </li>#}
{#  {% endif %}#}
{#  <br>#}
{#  <li>#}
{#    <a href="{% url 'catalog:index' %}">Home</a>#}
{#  </li>#}
{#  <li>#}
{#    <a href="{% url "catalog:author-list" %}">All authors</a>#}
{#  </li>#}
{#  <li>#}
{#    <a href="{% url "catalog:book-list" %}">All books</a>#}
{#  </li>#}
{#  <li>#}
{#    <a href="{% url "catalog:literary-format-list" %}">All literary formats</a>#}
{#  </li>#}
{#</ul>#}


{#Опис:#}
{#Розбір коду:#}
{#1. <ul class="sidebar-nav">#}
{#<ul> — тег, який створює невпорядкований список.#}
{#class="sidebar-nav" — додає до списку CSS-клас sidebar-nav, щоб можна було стилізувати цей список окремо за допомогою CSS.#}
{#2. <li>#}
{#Це елемент списку (list item). У цьому випадку кожен <li> містить посилання <a>.#}
{#Кількість <li> відповідає кількості пунктів у меню.#}
{#3. <a>#}
{#Тег <a> створює гіперпосилання. Атрибут href визначає адресу, на яку користувач буде перенаправлений після натискання на посилання.#}


{#Цей фрагмент коду є шаблоном на мові шаблонів Django, що створює бічну навігаційну панель у веб-додатку.#}
{##}
{#Опис коду:#}
{#<ul class="sidebar-nav">#}
{##}
{#Створюється ненумерований список (<ul>) з класом sidebar-nav.#}
{#Клас використовується для стилізації навігаційного меню за допомогою CSS.#}
{#<li> ... </li>#}
{##}
{#Кожен пункт списку представляє елемент навігаційного меню.#}
{#<a href="{% url 'catalog:index' %}">Home</a>#}
{##}
{#Створює посилання на головну сторінку каталогу.#}
{#{% url 'catalog:index' %} є Django-тегом, який будує URL за ім'ям маршруту catalog:index, визначеним у urls.py.#}
{#Текст посилання: "Home".#}
{#<a href="#">All authors</a>#}
{##}
{#Посилання на сторінку "All authors".#}
{#href="#" є заглушкою (поки сторінка або URL не реалізовані).#}
{#<a href="{% url "catalog:book-list" %}">All books</a>#}
{##}
{#Посилання на сторінку зі списком всіх книг.#}
{#{% url "catalog:book-list" %} будує URL для маршруту з ім'ям catalog:book-list.#}
{#<a href="{% url "catalog:literary-format-list" %}">All literary formats</a>#}
{##}
{#Посилання на сторінку зі списком літературних форматів (наприклад, роман, новела, поема).#}
{#{% url "catalog:literary-format-list" %} генерує URL для маршруту catalog:literary-format-list.#}
{#Закриваючий тег </ul>#}
{##}
{#Завершує ненумерований список.#}

{#Підсумок:#}
{#Цей код створює навігаційне меню, що дозволяє користувачу переходити між різними сторінками веб-застосунку:#}
{##}
{#Home – головна сторінка.#}
{#All authors – сторінка авторів (поки не реалізована).#}
{#All books – сторінка зі списком книг.#}
{#All literary formats – сторінка зі списком літературних форматів.#}
{#Django-тег {% url ... %} використовується для побудови динамічних посилань відповідно до маршруту, визначеного у urls.py#}

{###################################################}

{#Покращення templates#}

{#<ul class="sidebar-nav list-group">#}
{#  {% if user.is_authenticated %}#}
{#  <li class="list-group-item">#}
{#    User: {{ user.username }}#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#      <a href="{% url 'logout' %}">Logout</a>#}
{#    </li>#}
{#  {% else %}#}
{#    <li class="list-group-item">#}
{#      <a href="{% url 'login' %}">Login</a>#}
{#    </li>#}
{#  {% endif %}#}
{#  <br>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url 'catalog:index' %}">Home</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url "catalog:author-list" %}">All authors</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url "catalog:book-list" %}">All books</a>#}
{#  </li>#}
{#  <li class="list-group-item">#}
{#    <a href="{% url "catalog:literary-format-list" %}">All literary formats</a>#}
{#  </li>#}
{#</ul>#}

<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
  <li class="list-group-item">
    User: {{ user.username }}
  </li>
  <li class="list-group-item">
      <a href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}
  <br>
  <li class="list-group-item {% if request.resolver_match.view_name == 'catalog:index' %}
  active
  {% endif %}">
    <a href="{% url 'catalog:index' %}">Home</a>
  </li>
  <li class="list-group-item {% if request.resolver_match.view_name == 'catalog:author-list' %}
  active
  {% endif %}">
    <a href="{% url "catalog:author-list" %}">All authors</a>
  </li>
  <li class="list-group-item {% if request.resolver_match.view_name == 'catalog:book-list' %}
  active
  {% endif %}">
    <a href="{% url "catalog:book-list" %}">All books</a>
  </li>
  <li class="list-group-item {% if request.resolver_match.view_name == 'catalog:literary-format-list' %}
  active
  {% endif %}">
    <a href="{% url "catalog:literary-format-list" %}">All literary formats</a>
  </li>
</ul>


{#<!-- Navbar -->#}
{#<div class="container position-sticky z-index-sticky top-0">#}
{#  <div class="row">#}
{#    <div class="col-12">#}
{#      <nav#}
{#        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">#}
{#        <div class="container-fluid px-0">#}
{#          <a class="navbar-brand font-weight-bolder ms-sm-3"#}
{#            href="/" rel="tooltip"#}
{#            title="Designed and Coded by Creative Tim" data-placement="bottom">#}
{#            Soft UI Design System#}
{#          </a>#}
{#          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"#}
{#            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"#}
{#            aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon mt-2">#}
{#              <span class="navbar-toggler-bar bar1"></span>#}
{#              <span class="navbar-toggler-bar bar2"></span>#}
{#              <span class="navbar-toggler-bar bar3"></span>#}
{#            </span>#}
{#          </button>#}
{#          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">#}
{#            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">#}
{#              <li class="nav-item dropdown dropdown-hover mx-2">#}
{#                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"#}
{#                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                  Pages#}
{#                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">#}
{#                </a>#}
{#              </li>#}
{##}
{#              <li class="nav-item dropdown dropdown-hover mx-2">#}
{#                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"#}
{#                  href="javascript:;" id="dropdownMenuBlocks" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                  Blocks#}
{#                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1" />#}
{#                </a>#}
{#              </li>#}
{##}
{#              <li class="nav-item dropdown dropdown-hover mx-2">#}
{#                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"#}
{#                  href="javascript:;" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                  Docs#}
{#                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">#}
{#                </a>#}
{#              </li>#}
{##}
{#              {% if request.user.is_authenticated %}#}
{#              <li class="nav-item ms-lg-auto">#}
{#                <a class="nav-link nav-link-icon me-2"#}
{#                  href="{% url 'logout' %}">#}
{#                  <i class="fa fa-sign-out me-1"></i>#}
{#                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                    data-bs-placement="bottom" title="Logout">Logout</p>#}
{#                </a>#}
{#              </li>#}
{#              {% else %}#}
{#              <li class="nav-item ms-lg-auto">#}
{#                <a class="nav-link nav-link-icon me-2"#}
{#                  href="{% url 'login' %}">#}
{#                  <i class="fa fa-sign-in me-1"></i>#}
{#                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"#}
{#                    data-bs-placement="bottom" title="Login">Login</p>#}
{#                </a>#}
{#              </li>#}
{#              {% endif %}#}
{##}
{#              <li class="nav-item my-auto ms-3 ms-lg-0">#}
{#                <a href="https://appseed.us/product/soft-ui-design/django/" target="_blank"#}
{#                  class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Download</a>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </div>#}
{#      </nav>#}
{#      <!-- End Navbar -->#}
{#    </div>#}
{#  </div>#}
{#</div>#}