catalog/urls.py
from django.urls import path


from catalog.views import (
    index,
    LiteraryFormatListView,
    BookListView,
    BookCreateView,
    BookUpdateView,
    AuthorListView,
    AuthorDetailView,
    AuthorCreateView,
    BookDetailView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
#    test_session_view,
)

#   шлях, який оброблюється ф-єю  index
urlpatterns = [
    path("", index, name= "index"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name= "literary-format-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name= "literary-format-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name= "literary-format-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name= "literary-format-delete"),
    path("books/", BookListView.as_view(), name= "book-list"),
    path("books/create/", BookCreateView.as_view(), name= "book-create"),
    path("books/<int:pk>/", BookDetailView.as_view(), name= "book-detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name= "book-update"),
    path("authors/", AuthorListView.as_view(), name= "author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name= "author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name= "author-detail"),
    # path("books/<int:pk>", book_detail_view, name= "book-detail"),

#    path("test-session/", test_session_view, name= "test-session"),
]


app_name = "catalog"

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name

class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    groups = models.ManyToManyField(
        "auth.Group",
        related_name="author_groups",  # Унікальна назва
        blank=True
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="author_permissions",  # Унікальна назва
        blank=True
    )

    class Meta:
        ordering = ("username", )

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("catalog:author-detail", kwargs={"pk": self.pk})


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat, on_delete=models.CASCADE,
        related_name="books",
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ("title", )

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format.name})"


    # створення URL-адрес (посилання на конкретну книгу) в коді за допомогою функції reverse:

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from catalog.models import Author, Book


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "pseudonym",)


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Book
        fields = "__all__"

# Цей клас наслідується від просто Form, а не від ModelForm, тому що він не буде на пряму взаємодіяти з моделями.
class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by title"
            }
        )
    )

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import CreateView

from .forms import AuthorCreationForm, BookForm, BookSearchForm
from .models import Book, Author, LiteraryFormat


# додамо в нашу ф-цію змінну-лічильник(для підрахунку кількості входжень на нашу сторінку num_visits)
@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_books = Book.objects.count()  # кількість книжок
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_authors': num_authors,
        'num_literary_formats': num_literary_formats,
        'num_visits': num_visits + 1,
    }
    return render(request, "catalog/index.html", context=context)


# @login_required - підходить до FBV (Function Base Views), але не підходить до Class Base Views
# Для Class Base Views використовуються міксіни (Mixin) В нашему випадку викор. LoginRequiredMixin
# Таким чином ми Ми можемо обмежити доступ неавтентифікованим користувачам,
# застосувавши декоратор login_required до твоєї функції-представлення або
# LoginRequiredMixin — спосіб обмежити доступ у класових представленнях.
# Доступ до цих представлень отримають лише автентифіковані користувачі.

class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    queryset = Author.objects.prefetch_related('books')
    paginate_by = 2


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


# Іноді потрібно реалізувати можливість пошуку за певним параметром.
# Для цього потрібно ввести текст для пошуку та створити форму.
# на сторінку Book List нашого сайту,#}
# створимо Search(пошук) книги, додамо кастомні методи до класу BookListView:
class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2

# Також можна додати опцію, щоб введений текст зберігався.
    # Для цього потрібно змінити кастомний метод:
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        title = self.request.GET.get('title', "")
        context["title"] = title
        context["search_form"] = BookSearchForm(
            initial={'title': title}
        )
        return context

# реалізація пошуку: Необхідно зробити так: якщо ми передаємо пошукове слово, то queryset фільтрується
    # за цим словом; якщо ні — повертаються всі пости:

    # def get_queryset(self):
    #     title = self.request.GET.get("title")
    #     if title:
    #         return self.queryset.filter(title__icontains=title)
    #     return self.queryset

# Також ти можеш реалізувати такий пошук за допомогою форми:
    def get_queryset(self):
        queryset = Book.objects.select_related("format")
        form = BookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data['title'])
        return queryset





class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_confirm_delete.html"
    success_url = reverse_lazy("catalog:literary-format-list")


def test_session_view(request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        "<h1>Test Session</h1>"
        f"<h4>Session data: {request.session['book']}</h4>"

    )

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ author.first_name }} {{ author.last_name }}</h1>
  <p><strong>username: </strong>{{ author.username }}</p>
  <p><strong>Pseudonym: </strong>{{ author.pseudonym | default:"No pseudonym" }}</p>
  <div class="ml-3">
    <h3>Books:</h3>
    {% for book in author.books.all %}
      <hr>
      <p class="text-muted">{{ author.id }}</p>
      <p>{{ book.title }}</p>
    {% empty %}
      <p>No books!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Create Author</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{#{% block content %}#}
{#  <h1>Author List<a style="float: right" href="{% url 'catalog:author-create' %}">+</a></h1>#}
{#  {% if author_list %}#}
{#    <ul>#}
{#      {% for author in author_list %}#}
{#        <li><a href="{{author.get_absolute_url}}">{{ author.username }} {{ author.first_name }} {{ author.last_name }}</a></li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}
{#{% endblock %}#}


{% block content %}
  <h1>Author List<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:author-create' %}">+</a></h1>
  {% if author_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Full Name</th>
        <th>Username</th>
        <th>Pseudonym</th>
      </tr>
      {% for author in author_list %}
        <tr>
          <td>
            <a href="{{ author.get_absolute_url }}">{{ author.id }}</a>
          </td>
          <td>
            {{ author.first_name }} {{ author.last_name }}
          </td>
          <td>
            {{ author.username }}
          </td>
          <td>
            {{ author.pseudonym|default_if_none:"" }}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}



{#{% block content %}#}
{#🔹 Відкриває блок контенту, який буде підставлений у base.html або інший батьківський шаблон.#}
}
{#<h1>Author List<a style="float: right" href="{% url 'catalog:author-create' %}">+</a></h1>#}
{#🔹 Заголовок сторінки#}
{#🔹 Додає кнопку + (праворуч), яка веде на сторінку створення автора (author-create).#}

{#{% if author_list %}#}
{#🔹 Перевіряє, чи author_list не порожній. Якщо список авторів є, виводимо таблицю.#}

{#<table class="table">#}
{#  <tr>#}
{#    <th>ID</th>#}
{#    <th>Full Name</th>#}
{#    <th>Username</th>#}
{#    <th>Pseudonym</th>#}
{#  </tr>#}

{#🔹 Створює HTML-таблицю зі стовпцями:#}

{#ID#}
{#Full Name (ім'я + прізвище)#}
{#Username#}
{#Pseudonym#}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }} <a class="btn btn-secondary" style="float: right" href="{% url 'catalog:book-update' pk=book.id %}">Edit</a></h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Format: </strong>{{ book.format }}</p>
  <div class="ml-3">
    <h3>Authors:</h3>
    {% for author in book.authors.all %}
      <hr>
      <p class="text-muted">{{ author.id }}</p>
      <p>{{ author.first_name }} {{ author.last_name }}
      {% if author.pseudonym %}
        {{ author.pseudonym }}
      {% endif %}
      </p>
    {% empty %}
      <p>No authors!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{#{% extends "base.html" %}#}
{#{% block content %}#}
{#  <h1>Create Literary Format</h1>#}
{#  <form action="" method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Submit">#}
{#  </form>#}
{#{% endblock %}#}

{#Щоб відбулися зміни на сторинці потрібно додати до нашої форми бібліотеку crispy#}
{#змінити з {{ form.as_p }} на {{ form|crispy}} та додати(загрузити {% load crispy_forms_filters %}) #}
{#Тепер наша форма на сторінці змінилася#}
{#<input class="btn btn-primary" type="submit" value="Submit"> - змінимо кнопку "Submit"#}

{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{#{% block content %}#}
{#  <h1>Create Literary Format</h1>#}
{#  <form action="" method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    {{ form|crispy}}#}
{#    <input class="btn btn-primary" type="submit" value="Submit">#}
{#  </form>#}
{#{% endblock %}#}


{#Внесемо зміни на сторінку Literary Format List/#}

{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Book</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

{#{{ object|yesno:"Update, Create" }}#}
{#{{ }}: Це синтаксис Django для вставки значення змінної або результату фільтра в шаблон.#}
{#object:#}
{#Це змінна контексту, яка передається в шаблон. У випадку використання generic.CreateView або generic.UpdateView,#}
{#ця змінна зазвичай відповідає об'єкту, над яким виконуються дії.#}
{#Якщо це форма для створення нового об'єкта (CreateView), object буде None.#}
{#Якщо це форма для оновлення існуючого об'єкта (UpdateView), object містить сам об'єкт.#}
{#|yesno:"Update, Create":#}
{#Це фільтр Django, який повертає одне з двох слів залежно від того, чи є значення змінної True або False.#}
{#У цьому випадку:#}
{#Якщо object існує (тобто це UpdateView), буде вставлено слово Update.#}
{#Якщо object дорівнює None (тобто це CreateView), буде вставлено слово Create.#}

templates/catalog/book_list.html
{# створення URL-адрес (посилання на конкретну книгу) в коді за допомогою тега {% url %} #}
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Book List</h1>#}
{#  {% if book_list %}#}
{#    <ul>#}
{#      {% for book in book_list %}#}
{#        <li><a href="{% url "catalog:book-detail" book.id %}">{{ book.title }} ({{ book.price }}, {{ book.format }})</a></li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}
{#{% endblock %}#}


{## Детальний опис#}
{#{% extends "base.html" %}#}
{##}
{#Цей рядок означає, що шаблон розширює інший базовий шаблон base.html.#}
{#Базовий шаблон містить спільні елементи (шапка, меню, футер), а цей шаблон додає контент лише до блоку content.#}
{#{% block content %} і {% endblock %}#}
{##}
{#Блок content визначає місце, де відображатиметься конкретний контент (у цьому випадку список книг).#}
{#У базовому шаблоні є тег {% block content %}, куди вставляється цей код.#}
{#<h1>Book List</h1>#}
{##}
{#Заголовок сторінки: "Book List" (Список книг).#}
{#{% if book_list %}#}
{##}
{#Перевірка, чи переданий в шаблон список книг (book_list) містить дані.#}
{#Якщо список порожній, код усередині цієї умови не буде виконаний.#}
{#<ul> ... </ul>#}
{##}
{#HTML-список, який містить перелік книг.#}
{#{% for book in book_list %} і {% endfor %}#}
{##}
{#Цикл, який перебирає всі елементи списку book_list.#}
{#Кожен елемент списку (об’єкт книги) доступний у змінній book.#}
{#<li>#}
{##}
{#Кожна книга відображається як окремий пункт списку (<li>).#}
{#<a href="{% url "catalog:book-detail" book.id %}">#}
{##}
{#Створює посилання на деталі книги.#}
{#Тег {% url "catalog:book-detail" book.id %} генерує URL для перегляду деталей конкретної книги на основі її id.#}
{#"catalog:book-detail" — це ім’я маршруту, визначеного в urls.py.#}
{#{{ book.title }} ({{ book.price }}, {{ book.format }})#}
{##}
{#Виводить дані про книгу:#}
{#book.title — назва книги.#}
{#book.price — ціна книги.#}
{#book.format — формат книги#}


{# створення URL-адрес (посилання на конкретну книгу) в коді за допомогою функції reverse #}
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Book List <a style="float: right" href="{% url 'catalog:book-create' %}">+</a></h1>#}
{#  {% if book_list %}#}
{#    <ul>#}
{#      {% for book in book_list %}#}
{#        <li><a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.price }}, {{ book.format }})</a></li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}
{#{% endblock %}#}


{#Цей шаблон є частиною HTML-сторінки для відображення списку книг, де створення URL-адрес для деталей книги#}
{#здійснюється через метод get_absolute_url у моделі Book. #}
{#<a href="{{ book.get_absolute_url }}">#}
{##}
{#Використовується метод get_absolute_url моделі Book для створення URL-адреси.#}
{#Цей метод повинен бути реалізований у моделі Book і зазвичай виглядає так:#}
{##}
{#У models.py:#}
{#from django.urls import reverse#}
{##}
{#class Book(models.Model):#}
{#    title = models.CharField(max_length=200)#}
{#    price = models.DecimalField(max_digits=6, decimal_places=2)#}
{#    format = models.CharField(max_length=50)#}
{##}
{#    def get_absolute_url(self):#}
{#        return reverse("catalog:book-detail", args=[str(self.id)])#}
{#Метод повертає URL на основі маршруту catalog:book-detail, підставляючи ідентифікатор книги (id).#}
{#{{ book.title }} ({{ book.price }}, {{ book.format }})#}
{##}
{#Виводить інформацію про книгу:#}
{#book.title — назва книги.#}
{#book.price — ціна книги.#}
{#book.format — формат книги #}


{##############################################################3#}

{#Django Advanced #}
{#Додамо нову фічу на сторінку Book List нашого сайту,#}
{#а саме Search(пошук) книги: в верхній частині  сторінки ми стоворемо поле, в яке вводимо title книги - і тоді #}
{#на сторінці мають відобразитися лише ті записи, які підходять під цей пошуковий запис #}
{#Оскільки мова йде про поле введення інформації - то ми будемо використовувати форми  (файл form.py) #}

{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{##}
{#{% block content %}#}
{#  <h1>Book List <a style="float: right" href="{% url 'catalog:book-create' %}">+</a></h1>#}
{#  <form method="get" action="" class="form-inline">#}
{#    {{ search_form|crispy }}#}
{#    <input class="btn-secondary" type="submit" value="🕵🏼‍♂️">#}
{#  </form>#}
{#  {% if book_list %}#}
{#    <ul>#}
{#      {% for book in book_list %}#}
{#        <li><a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.price }}, {{ book.format }})</a></li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}
{#{% endblock %}#}



{#######################################################}

{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Book List <a class="btn btn-secondary" style="float: right" href="{% url 'catalog:book-create' %}">+</a></h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn-secondary" type="submit" value="🕵🏼‍♂️">
  </form>
  {% if book_list %}
    
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Format</th>
      </tr>
      {% for book in book_list %}
        <tr>
          <td>
            <a href="{{ book.get_absolute_url }}">{{ book.id }}</a>
          </td>
          <td>
            {{ book.title }}
          </td>
          <td>
            {{ book.price }}
          </td>
          <td>
            {{ book.format }}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
  <title>Home page</title>
{% endblock %}
{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to the Greatest Library!</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_literary_formats }}</li>
  </ul>

  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>

{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete Literary Format</h1>
  
  <p>Are you sure you want to delete the literary format: {{ literaryformat }}?</p>
  <p><i>All Books with this literary format will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn badge-danger"/>
  </form>
  
{% endblock %}

templates/catalog/literary_format_list.html
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Literary Format List<a style="float: right" href="{% url 'catalog:literary-format-create' %}">+</a></h1>#}
{#  #}
{#  {% if literary_format_list %}#}
{#    <ul>#}
{#      {% for literary_format in literary_format_list %}#}
{#        <li>{{literary_format.name}}</li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% else %}#}
{#    <p>There are no Literary formats in Library</p>#}
{#  {% endif %}#}
{#{% endblock %}#}


{#{% for literary_format in literary_format_list %} - ітеруємся через цикл for по всьому списку literary_format_list#}
{#та виводимо кожний формат (literary_format) на нашу сторінку#}

{#Додаємо умову, що якщо ми маємо літер.формати,#}
{#то мибудемо їх виводити за доп. циклу for#}

{#{% else %} - якщо literary_format_list немає, то виводимо текст:#}
{#There are no Literary formats in Library#}

{#{% for %}, {% if %}, {% else %} - це деякі django-шаблонізатори#}



{#Для спрощення коду замість {% if literary_format_list %} та {% else %}#}
{#можна використати {% empty %} - і матимемо таки же результат (Дивитись нижче)#}

{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Literary Format List</h1>#}
{#  <ul>#}
{#    {% for literary_format in literary_format_list %}#}
{#      <li>{{literary_format.name}}</li>#}
{#    {% empty %}#}
{#      <p>There are no Literary formats in Library</p>#}
{#    {% endfor %}#}
{#  </ul>#}
{#{% endblock %}#}


{#<a style="float: right" href="{% url 'catalog:literary-format-create' %}">+</a>#}
{##}
{#<a>: Це тег посилання, який вказує на URL, що веде до сторінки створення нового літературного формату.#}
{#style="float: right": Використовується для CSS-оформлення, щоб посилання відображалося в правій частині рядка.#}
{#  Це робить інтерфейс більш структурованим.#}
{#href="{% url 'catalog:literary-format-create' %}": Django-шаблонна конструкція {% url %} генерує URL #}
{#  на основі іменованого маршруту.#}
{#У цьому випадку, вона генерує посилання для маршруту з ім'ям "catalog:literary-format-create".#}
{#Ім'я маршруту визначене у вашому файлі urls.py:#}
{#python#}
{#Копировать код#}
{#path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-format-create"),#}
{#>+</a>: Текст посилання. У цьому випадку це символ "+", який зазвичай використовується#}
{#для позначення створення нового запису.#}

{############################################################}

{#Спосіб поєднання наших форм із bootstrap(бутстрап) #}
{#для того, щоб використовувати bootstrap разом з Django-формами #}
{#ми використовуємо окрему бібліотеку django-crispy-forms, #}
{#ось посилання:   https://django-crispy-forms.readthedocs.io/en/latest/index.html #}

{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Literary Format List<a style="float: right" href="{% url 'catalog:literary-format-create' %}">+</a></h1>#}
{#  #}
{#  {% if literary_format_list %}#}
{#    <ul>#}
{#      {% for literary_format in literary_format_list %}#}
{#        <li>{{literary_format.name}}</li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% else %}#}
{#    <p>There are no Literary formats in Library</p>#}
{#  {% endif %}#}
{#{% endblock %}#}

{#Відредагуємо наш код, щоб прямо на цій сторінці було зручно видаляти литературні формати#}

{% extends "base.html" %}

{% block content %}
  <h1>Literary Format List<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:literary-format-create' %}">+</a></h1>
  
  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for literary_format in literary_format_list %}
        <tr>
          <td>
            {{ literary_format.id }}
          </td>
          <td>
            {{ literary_format.name }}
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-update' pk=literary_format.id %}">UPDATE</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-delete' pk=literary_format.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}  
    </table>
  {% else %}
    <p>There are no Literary formats in Library</p>
  {% endif %}
{% endblock %}